### ISSUE TITLE
Strange autocomplete behavior when using the default namespace

### ISSUE THREAD

**Issue by IObert** [SAP/ui5-language-assistant#228]
The autocomplete works fine in the manifest file and when I use “named” namespaces. The only thing that doesn’t seem to work is when I want to use tags from the default namespace (like xmlns=”sap.m”). In this case, autocomplete is not working. 

After playing around for a while, I noticed that it "works" when I open a "nested tag" (see GIF). This might be related to my VS Code settings.

![2020-07-09_10-29-03-1](https://user-images.githubusercontent.com/1873245/87017095-d68a4b80-c1cf-11ea-845a-ebb8cc8579c1.gif)

**Comment by bd82** [comment]
I suspect your issue is caused by the duplicate cursor mode.
This is not a feature of the UI5-Language-Assistant, but I believe it may be related to some other FIORI VSCode extension.

Can you try reproducing after first un-installing all other VSCode extensions from your VSCode?

**Comment by IObert** [comment]
Thanks for your answer. You are right, it disabled my extensions one by one and found out that this issue is triggered by the *SAP Fiori tools - XML Annotation Language Server* extension. I would assume that it is not uncommon to use both extensions at the same time. Can you please follow up internally what causes this side effect?

**Comment by bd82** [comment]
I think you can workaround the issue if you press "ESC" after opening a new tag ("<") to **exit** the double cursor mode **before**, requesting content assist.

I also think the cause is the implementation of automatic alignment of tags by using duplicate cursors.
I've heard this feature will be limited only to annotation.xml files in the future which will solve the problem.

From the UI5-Lang-Assist side the auto-complete APIs used are the Language Server Protocol APIs, so there is nothing unique on this side...

I hope that in the future we will have a different implementation of XML tags auto-alignment
in the XML-Toolkit VSCode ext. but there are no timelines that I am aware of currently...
- https://marketplace.visualstudio.com/items?itemName=SAPOSS.xml-toolkit
 

Cheers.
Shahar.
