### ISSUE TITLE
Sometimes valid Tags are marked invalid

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP/ui5-language-assistant#406]
I sometimes get errors in the view validation. 
For example for the XML Tag BadgeCustomData I get the following message: 
`The "BadgeCustomData" class doesn't exist in the "sap.m" namespace.`

But it exists and works: https://sapui5.hana.ondemand.com/#/api/sap.m.BadgeCustomData

Any suggestions how to fix this or is it a bug?

**Comment by bd82** [comment]
Hello @MichaelFlucher 

The problem is that this extension is using (hard-coded) metadata of older (1.71 ?) version of UI5 and does not currently support
newer versions.

The `BadgeCustomData` class seem to have been added in 1.80 and this is why the Extension does not recognize it.

- 
![image](https://user-images.githubusercontent.com/4233843/120171321-9c240580-c20a-11eb-87b9-1f80a39b3936.png)

Related issue #245 (see more details there)
