### ISSUE TITLE
The "SmartLabel" class doesn't exist in the "sap.ui.comp.smartfield" namespace.

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-language-assistant#430]
`sap.ui.comp.smartfield.SmartLabel` is not explicitly exposed by the framework although the documentation itself shows its usage in combination with the `SmartField` control:
https://sapui5.hana.ondemand.com/#/api/sap.ui.comp.smartfield.SmartField

Therefore user would expect this syntax to be supported. Unfortunately this is not true:

![image](https://user-images.githubusercontent.com/26189327/138678078-2e06ecdb-4597-4529-98cf-ebaa97d74b69.png)

**Comment by boghyon** [comment]
I don't think there is anything UI5 Language Assistant can do here. According to the [`SmartField` API reference:](https://ui5.sap.com/#/api/sap.ui.comp.smartfield.SmartField)

> Although the **`sap.ui.comp.smartfield.SmartLabel` is a private**/internal control, the following basic use is **allowed by applications** for labeling the `SmartField` control.

I find this highly questionable since framework/control developers are supposed to adhere to the [JSDoc Visibility Tags](https://sdk.openui5.org/topic/b0d5fe2f1b0b497cbd67cd5a1d35fa4c) guidelines. And according to the [Compatibility Rules](https://ui5.sap.com/#/topic/91f087396f4d1014b6dd926db0e91070):

> [Application developers should] **never** use or override "private" functions that aren't part of the [API Reference](https://ui5.sap.com/#/api/sap.ui).

**Comment by petermuessig** [comment]
The UI5 Language Assistant only displays the public API. Experimental, protected, restricted and private API will not be shown. All infos used by the UI5 Language Assistant is built on top of the JSDoc of UI5. If the API is available there publically it can be used. 

BTW: The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469
