### ISSUE TITLE
View class doesn't exist in the 'sap.ui.core' namespace

### ISSUE THREAD

**Issue by Kai87de** [SAP/ui5-language-assistant#462]
Dear 'ui5-language-assistant' dev team,

Using BAS following error appears since several weeks...
![image](https://user-images.githubusercontent.com/97990083/178712922-2acc8db9-7bb3-47a5-885a-9fc12359531e.png)

Could you please check?

Regards & Thanks
Kai

**Comment by boghyon** [comment]
The reported error is 100% correct. There is **no module named `"sap.ui.core.View"`**. But **[there is <code>sap.ui.core<strong>.mvc</strong>.View</code>.](https://sdk.openui5.org/api/sap.ui.core.mvc.View)** So it should be:

```xml
<mvc:View xmlns:mvc="sap.ui.core.mvc">
<!-- <core:View xmlns:core="sap.ui.core"> is wrong -->
```

[Running the **Support Assistant**](https://sdk.openui5.org/topic/57ccd7d7103640e3a187ed55e1d2c163) would've also reported the [same issue in the XML view definition](https://github.com/SAP/openui5/blob/d72de68267e9c08a6c4ff7ef7d52fb5cc1895d07/src/sap.ui.core/src/sap/ui/core/rules/View.support.js#L28-L62).

See also:

- Comment by @akudev in https://github.com/SAP/openui5/issues/541#issuecomment-123652366

- Your browser console at runtime:

  + Error log since OpenUI5 1.102.0:
    > XMLView's root node <strong>must</strong> be '`View`' or '`XMLView`' and <strong>have the namespace '<code>sap.ui.core.mvc</code>'</strong> [...].
  + Error log previously:
    > XMLView root node <strong>must have the '<code>sap.ui.core.mvc</code>' namespace</strong>, not [...].

**Comment by petermuessig** [comment]
As @boghyon stated, this is not an issue of the code completion. The `View` is part of the `sap.ui.core.mvc` namespace.

**Comment by Kai87de** [comment]
Thanks for your help. Will check that again.. btw. I think that my Fiori App was generated once by WebIDE
