### ISSUE TITLE
The UI5 Language Assistant server crashed

### ISSUE THREAD

**Issue by NAVI-91** [SAP/ui5-language-assistant#473]
v3.2.0 throws below error.

![image](https://user-images.githubusercontent.com/17800881/185148189-97146543-acc6-4d87-b4bc-255f76026f0b.png)

**Comment by petermuessig** [comment]
My bad - I fixed that with the PR #472 - I noticed that directly after the release and after some discussions with different parties we decided to change also the decision for the UI5 version based on the `minUI5Version` in the `manifest.json` rather than the `ui5.yaml` and an additional one in the `package.json`. In addition, with the PR above the version is also negotiated and will be resolved to the next closest supported and available version + a new `StatusBarItem` which indicates the UI5 runtime version to be used for the XML code completion. I can release a patch soon but there is another PR waiting for review #475 to support proxies...

**Comment by petermuessig** [comment]
The new VSIX 3.2.1 will be available soon. Unfortunately, the release creation for GH releases doesn't work right now.

**Comment by petermuessig** [comment]
Uploaded the VSIX 3.2.1 manually due to some release issue:
https://github.com/SAP/ui5-language-assistant/releases/tag/v3.2.1

Issue should be solved with it.
