### ISSUE TITLE
vsix 3.2.0 published ETA

### ISSUE THREAD

**Issue by piejanssens** [SAP/ui5-language-assistant#476]
What are you waiting for? 😄 

💡 https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions

**Comment by petermuessig** [comment]
Hi @piejanssens , a transition to GitHub Actions is in discussion (with @uxkjaer and @bd82). For now, the UI5 Language Assistant is using Circle CI. For the availability in the marketplace we are currently discussion this internally since we need to follow some processes. Also this should become more lightweight in future. Stay tuned...
