### ISSUE TITLE
Not covered: sap.fe.macros.FormElement

### ISSUE THREAD

**Issue by juergenbosch** [SAP/ui5-language-assistant#522]
If is use the sap.fe.macros.FormElement as in the example:
https://ui5.sap.com/test-resources/sap/fe/core/fpmExplorer/index.html#/buildingBlocks/formElement/formElementLabel

The following errors are in the VSCode Problems View:
The "FormElement" class is under the "formElements" aggregation and must match the "FormElement" type.

**Comment by petermuessig** [comment]
@tobiasqueck can you check this issue here? It is related to the [`sap.fe.macros.form.FormElement`](https://ui5.sap.com/resources/sap/fe/macros/form/FormElement.metadata-dbg.js). In the usage example above the `FormElement` is used from the `sap.fe.macros` namespace rather than `sap.fe.macros.form` and from inheritance it doesn't match the [`sap.ui.layout.form.FormElement`](https://ui5.sap.com/#/api/sap.ui.layout.form.FormContainer%23aggregations) which is expected. This is the same issue as we discussed in another place...

**Comment by c-kobo** [comment]
Thanks for bringing this up. We are aware of this and already looking into it.
