### ISSUE TITLE
Error "An error has occurred building context. Please open an issue" in VSCode

### ISSUE THREAD

**Issue by kirilllavrenyukfioneer** [SAP/ui5-language-assistant#606]
Hello,

After I cloned my app from the GitHub repo and opened it in VSCode I received an error "An error has occurred building context. Please open an issue" and no errors are shown related to the code check.

![image](https://github.com/SAP/ui5-language-assistant/assets/123752828/8a88d349-bf3a-418d-9267-eda1d13f16ad)

In the same time I have few more applications I'm working with and there no such error appeared.

I admit that maybe I'm doing something wrong, but don't know how to solve it.
Will be glad if you can help with it.

Thank you!

Best regards,
Kirill

**Comment by MN-public** [comment]
Hi Kirill,
we would need to have your project and know which min ui5 version you have in the manifest to reproduce the issue. Also the version of UI5 language assistant installed in your environment would be helpful.
If you cannot add your project here due to security reasons, please feel free to open the ticket for the component CA-UX-IDE
Thanks
Mariana

**Comment by kirilllavrenyukfioneer** [comment]
Hi @MN-public,

Could you check if you have access to this repository:
https://github.tools.sap/FIORI-FSPE-1909/fs.pe.fxtradereporting

Best regards,
Kirill

**Comment by kirilllavrenyukfioneer** [comment]
Hello Mariana.

Thanks for the analysis you've done and for provided solution.

Best regards,
Kirill
