### ISSUE TITLE
Language Assistant error occurres when building context when creating application with @sap/generator-fiori-freestyle

### ISSUE THREAD

**Issue by Debunair** [SAP/ui5-language-assistant#700]
I created a Fiori Freestyle Project the "Create Project from Template" option using the BAS. With that I created a Fiori Freestyle application (v. 1.12.5).

The application details:
|**App Generator** @sap/generator-fiori-freestyle|
|**App Generator Version**1.12.5|
|**Generation Platform** SAP Business Application Studio|
|**Template Used**simple|
|**Service Type**SAP System (ABAP On Premise)|
|**Service URL** <SERVICE_URL>|
|**Module Name** MODULE_NAME>|
|**Application Title** <APPLICATION_TITLE>|
|**Namespace** <NAMESPACE>|
|**UI5 Theme** sap_horizon|
|**UI5 Version** 1.121.1|
|**Enable Code Assist Libraries** True|
|**Enable TypeScript** False|
|**Add Eslint configuration** True

After creating the project and opening an XML File in the editor, the error message: "An error has occurred building context. Please open an issue." The extension does not work for the project.

**Comment by MN-public** [comment]
@Debunair 
Thanks for reporting the issue. The fix is prepared and can be tested using the  [release v4.0.55](https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.55).
Feel free to install the UI5 Language Assistant from this vsix, test the fix and let us know the result/close the issue. 
Alternatively, you can wait a few days until the version with this fix is delivered to VSC marketplace and SAP BAS.

**Comment by MN-public** [comment]
The fix is delivered, please let us know if it does not work for you
